os:
  - linux
services:
  - docker
env:
    global:
        - JHI_JDK=8
        - JHI_DISABLE_WEBPACK_LOGS=true
before_install:
    - |
        if [[ $JHI_JDK = '11' ]]; then
            echo '*** Using OpenJDK 11'
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
            java -version
        else
            echo '*** Using OpenJDK 8 by default'
        fi
    - java -version
install:
  - docker build -t jhipster/jhipster-registry:travis .
  - docker images
  - docker run --name jhipster-registry -p 8761:8761 -d -t jhipster/jhipster-registry:travis
script:
  - sleep 90
  - docker ps
  - docker logs jhipster-registry
  - curl -v http://localhost:8761
